### ISSUE TITLE
a new problem

### ISSUE THREAD

**Issue by duchuAz** [zyairelai/futures-jackrabbit#10]
Traceback (most recent call last):
  File "run.py", line 12, in <module>
    if binance_futures.position_information()[0].get('marginType') != "cross": binance_futures.change_margin_to_CROSSED()
  File "/home/ubuntu/futures-omax/binance_futures.py", line 18, in position_information
    def position_information()      : return client.futures_position_information(symbol=config.pair, timestamp=get_timestamp())
  File "/usr/local/lib/python3.8/dist-packages/binance/client.py", line 5070, in futures_position_information
    return self._request_futures_api('get', 'positionRisk', True, data=params)
  File "/usr/local/lib/python3.8/dist-packages/binance/client.py", line 222, in _request_futures_api
    return self._request(method, uri, signed, True, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/binance/client.py", line 197, in _request
    return self._handle_response()
  File "/usr/local/lib/python3.8/dist-packages/binance/client.py", line 230, in _handle_response
    raise BinanceAPIException(self.response)
binance.exceptions.BinanceAPIException: APIError(code=-1003): Way too many requests; IP(***.***.***.***) banned until 1615183669840. Please use the websocket for live updates to avoid bans.

**Comment by zyairelai** [comment]
Do you mind to tell me how many pairs are you running together at the same time?

**Comment by duchuAz** [comment]
I have run 4

**Comment by zyairelai** [comment]
Are you running other programs that requires Binance API?
Binance API has limits, a stress level of 1200 weights per minute.

https://binance-docs.github.io/apidocs/futures/en/#limits

My program should take around 150-200 weights per run, last time I was running 6 pairs at the same time and no issue.
Currently seem like your IP address is being banned for 3 days by Binance. 

Maybe you can try this again 2 days later, and stop running other programs that requires Binance API, or run less pairs.
